### ISSUE TITLE
`NewRelic.removeAllAttributes`  causes a runtime crash

### ISSUE THREAD

**Issue by nsuriadi** [newrelic/newrelic-android-agent#312] opened 2024-11-20 06:00 UTC
## Description

Calling `NewRelic.removeAllAttributes()` when `AnalyticsController` hasn't been initialized will throw a `NullPointerException`

## Steps to Reproduce

This happened in our app after `NewRelic.start` has been called but this can be reproduced by

1. Calling `NewRelic.removeAllAttributes()` without calling `NewRelic.start`
2. Observe the crash

## Expected Behavior

`NewRelic.removeAllAttributes()` returning `false` instead

## Relevant Logs / Console output

```Logcat
2024-11-20 16:38:41.762 26487-26487 newrelic                com.example.debug                 W  Analytics controller is not initialized!
2024-11-20 16:38:41.766 26487-26487 newrelic                com.example.debug                 W  Analytics controller is not initialized!
2024-11-20 16:38:41.766 26487-26487 newrelic                com.example.debug                 W  Analytics controller is not initialized!
```

_**Stack Trace**_

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int com.newrelic.agent.android.analytics.AnalyticsAttributeStore.count()' on a null object reference
       at com.newrelic.agent.android.analytics.AnalyticsControllerImpl.removeAllAttributes(AnalyticsControllerImpl.java:607)
       at com.newrelic.agent.android.NewRelic.removeAllAttributes(NewRelic.java:872)
```

## Your Environment

**OS:** Android 14
**New Relic Agent:** 7.5.0

## Additional context

It looks like `attributeStore` may have been [referenced](https://github.com/newrelic/newrelic-android-agent/blob/be50b4bfaa21086bc1c1e0e59206ff59946ce2de/agent-core/src/main/java/com/newrelic/agent/android/analytics/AnalyticsControllerImpl.java#L607-L611) for logging purposes (prior to it being instantiated)

**Comment by ndesai-newrelic** [comment] 2024-12-06 20:15
the issue is fixed in latest android agent release 7.6.2.

**Closed** 2024-12-06 20:16 UTC
Labels: bug
